# Generated by Django 5.2.5 on 2025-10-01 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('watch', 'Watch'), ('belt', 'Belt'), ('shirt', 'Shirt'), ('pants', 'Pants'), ('bag', 'Bag'), ('earphone', 'Earphone')], default='update', max_length=255),
        ),
    ]
